version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    volumes:
      - mongodata:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 
  elasticsearch:
    # Refer https://www.docker.elastic.co/#
    # using '-oss' for 100% Apache 2.0 code. i.e. no x-pack. Refer https://www.elastic.co/what-is/open-x-pack
    # https://www.elastic.co/guide/en/elasticsearch/reference/7.3/docker.html
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.1
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
#      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  kibana:
    # using '-oss' for 100% Apache 2.0 code. i.e. no x-pack. Refer https://www.elastic.co/what-is/open-x-pack
    # https://www.elastic.co/guide/en/kibana/7.3/docker.html 
    image: docker.elastic.co/kibana/kibana-oss:7.3.1
    restart: always
    ports:
      - 5601:5601
#    volumes:
#      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: "benchmarks"
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: 
      ELASTICSEARCH_PASSWORD: 
#  logstash:
#   # TODO: Use it for https://github.com/phutchins/logstash-input-mongodb
#    image: docker.elastic.co/logstash/logstasg-oss:7.3.1
#    restart: always
  elastichq:
    # http://docs.elastichq.org/installation.html
    image: elastichq/elasticsearch-hq
    restart: always
    volumes:
      - eshqdata:/src/db
    ports:
      - 5000:5000
    environment:
      HQ_DEFAULT_URL: http://localhost:9200
      HQ_ENABLE_SSL: "False"
#      HQ_CA_CERTS: /path/to/your/ca.crt

volumes:
  mongodata:
    driver: local
  esdata:
    driver: local
  eshqdata:
    driver: local
